### ISSUE TITLE
Can't schedule on nodes with taints: toleration missing

### ISSUE THREAD

**Issue by Sapd** [exoscale/exoscale-csi-driver#38]
### Current Behavior

When using taints on nodes, for example:
```bash
exo compute sks nodepool add de-blocktest tainttest --security-group sks-security-group --taint dedicated="myapp:NoSchedule" -z at-vie-1
```

the CSI stops working on the respective nodes. Volumes cannot be attached.

The problem is that
```yaml
      tolerations:
      - operator: Exists
```

is missing in the specs section of `daemonset/exoscale-csi-node` and `deployment/exoscale-csi-controller`. As such they are not scheduled on the respective nodes.

All other objects in the `kube-system` namespace are setting it, for example calico, coredns etc.
Google cloud for example also sets it: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/26321e415324d49cb4e80b8b1669ff6eec14feb8/deploy/kubernetes/base/node_linux/node.yaml#L107

### Expected Behavior

Attaching volumes should work on nodes with taints.

### CSI Version

v0.29.6

### Kubernetes version

v1.30.2

**Comment by PhilippeChepy** [comment]
This issue is for discussion internally.
Closing.

**Comment by brutasse** [comment]
For the record, tolerations were added in #46 and are also part of the CSI addon on SKS.
