### ISSUE TITLE
[Bug]: StorageClass `exoscale-sbs` is not set as default

### ISSUE THREAD

**Issue by nhedger** [exoscale/exoscale-csi-driver#43]
### Current Behavior

The `exoscale-sbs` storage class created by the Exoscale CSI driver is not set as default.

The [docs](https://community.exoscale.com/documentation/block-storage/csi/#default-storageclass) specify the following:

> ### Default StorageClass
> If you enable the CSI addon through any of the methods above, a **default StorageClass named exoscale-sbs will be created in your cluster**. Note that the reclaimPolicy is set to Delete which means, that if you delete a PersistentVolumeClaim(PVC) the backing block storage volume will be deleted automatically. If this is not the behaviour you expect, you will need to create and use your own StorageClass with reclaimPolicy set to Retain.

But on a freshly created SKS cluster, the `exoscale-sbs` StorageClass does not have the `storageclass.kubernetes.io/is-default-class` annotation set to `true`, which means that there are no default storage classes.

### Expected Behavior

When provisioning a fresh cluster, the `exoscale-sbs` storage class is actually set as default.

### Steps To Reproduce

1. Create a fresh SKS cluster
2. Retrieve the storage class `kubectl get storageclass exoscale-sbs -o yaml`
3. See that the resource is missing the `storageclass.kubernetes.io/is-default-class` annotation

### CSI Version

Don't know how to retrieve this info

### Kubernetes version

v1.31.0

**Comment by sauterp** [comment]
Hey @nhedger 
thank you for noticing this! Indeed we don't set the default storage class and we forgot to update these docs accordingly. It's actually possible in kubernetes to set multiple storage classes as the default. I'm not sure whether they will ever fix this, as it's just an annotation [see this comment](https://github.com/pulumi/pulumi-eks/issues/141#issuecomment-503348329).
Therefore we decided not to set the default storage class, as we'd need to check whether there is already a default and then we'd need to decide whether to change it. It's hard to decide which option serves the user better in this situation and adds complexity to our implementation with very little extra value.
At least that was our conclusion. Would you mind if we simply updated the docs? Do you rely heavily on a default being available? (it only saves you two lines of yaml)

**Comment by nhedger** [comment]
Hey @sauterp,

> Therefore we decided not to set the default storage class, as we'd need to check whether there is already a default and then we'd need to decide whether to change it.

Do you mean that when the cluster is provisioned for the first time, there could be another storage class already defined (apart from `exoscale-sbs`)? If so, I guess it makes sense indeed, and updating the docs should be enough!

**Comment by sauterp** [comment]
It's actually possible to enable the CSI on an already existing cluster. In that case: `exo compute sks update --enable-csi-addon`. So it's possible to enable the CSI on a cluster where another storage provider has already been installed, like longhorn for example. And perhaps that other provider creates a storage class and sets it as the default. In this case, we would end up in the situation I described above, which we'd like to avoid.

Additionally we don't think it's good for users to rely on there being a default storage class. We should always explicitly specify in a manifest what storage class we would like to use, so that we make a conscious choice where we store our persistent data.

**Comment by sauterp** [comment]
The documentation is updated.
